services:
  backend:
    build:
      context: ./Backend
      args:
        MODE: development
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db_data:5432/${DB_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - db_data

  frontend:
    build:
      context: ./Frontend
      args:
        MODE: development
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:3000

  db_data:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  db_data:
    driver: local

networks:
  app-network: